from pydantic import BaseModel

class InputModel(BaseModel):
    aircraftSerNum1: float
    amscChBasHealthStatus1: float
    amscChBasHealthStatus2: float
    amscHprsovDrivF1: float
    amscHprsovDrivF2: float
    amscPrsovDrivF1: float
    amscPrsovDrivF2: float
    basBleedLowPressF1: float
    basBleedLowPressF2: float
    basBleedLowTempF1: float
    basBleedLowTempF2: float
    basBleedOverPressF1: float
    basBleedOverPressF2: float
    basBleedOverTempF1: float
    basBleedOverTempF2: float
    bleedAcsBleedConfigStatus1: float
    bleedAcsBleedConfigStatus2: float
    bleedFavTmCmd1: float
    bleedFavTmCmd2: float
    bleedFavTmFbk1: float
    bleedFavTmFbk2: float
    bleedHprsovCmdStatus1: float
    bleedHprsovCmdStatus2: float
    bleedHprsovOpPosStatus1: float
    bleedHprsovOpPosStatus2: float
    bleedMonPress1: float
    bleedMonPress2: float
    bleedOnStatus1: float
    bleedOnStatus2: float
    bleedOutTemp1: float
    bleedOutTemp2: float
    bleedOutTempTarget1: float
    bleedOutTempTarget2: float
    bleedOverpressCas1: float
    bleedOverpressCas2: float
    bleedPrecoolDiffPress1: float
    bleedPrecoolDiffPress2: float
    bleedPrsovClPosStatus1: float
    bleedPrsovClPosStatus2: float
    bleedPrsovFbk1: float
    bleedPrsovFbk2: float
    bleedPrsovOpPosStatus1: float
    bleedPrsovOpPosStatus2: float
    bleedPrsovTmCmd1: float
    bleedPrsovTmCmd2: float
    bleedSingleOperation1: float
    bleedSingleOperation2: float
    bleedSwPress1: float
    bleedSwPress2: float
    correctedCoreSpeed1a: float
    correctedCoreSpeed3a: float
    correctedN1Speed1a: float
    correctedN1Speed3a: float
    messageInhibitPhases1: float
    phaseOfFlight1: float
    phaseOfFlightNavigation1: float
    sfyBasFaultWord1Bit131: float
    sfyBasFaultWord1Bit132: float
    pressAltitude1: float
    pressAltitude2: float
    pressAltitude3: float
    pressAltitude4: float
    wOW1: float
    wOW3: float